---
name: Lint chart

on: [ pull_request, push ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true

      - name: Run helm lint
        run: helm lint deploy/cert-manager-webhook-hostingde/ --strict
